import React from "react";
import "../App.css";

const Story = () => (
  <div className="story-page" style={{ padding: "2rem", maxWidth: "700px", margin: "0 auto" }}>
    <h1>Our Story</h1>
    <p style={{ whiteSpace: "pre-line", fontSize: "1.1rem", lineHeight: "1.7" }}>
IT ALL STARTED WITH A BOY WHO HAD A DREAM — A DREAM TO CREATE SOMETHING OF HIS OWN IN THE WORLD OF FASHION.

WHAT BEGAN AS JUST AN IDEA SLOWLY GREW INTO A VISION: TO BUILD A BRAND THAT BLENDS PREMIUM QUALITY WITH EVERYDAY STYLE.

AFTER YEARS OF PASSION, PERSISTENCE, AND LEARNING, THAT DREAM BECAME LH. MORE THAN OVERSIZED TEES, LH IS ABOUT EXPRESSING INDIVIDUALITY, CONFIDENCE, AND COMFORT. EVERY DESIGN REFLECTS THE JOURNEY — FROM DREAM TO REALITY.

AT LH, WE BELIEVE FASHION SHOULDN'T BE OUT OF REACH. THAT'S WHY WE BRING YOU LUXURY YOU CAN FEEL, STYLE YOU CAN TRUST, AND PRICES THAT STAY REAL.

FROM ONE DREAM TO MANY WARDROBES — WELCOME TO LH.
    </p>
  </div>
);

export default Story;
